### ISSUE TITLE
Remove usernames in documentation

### ISSUE THREAD

**Issue by kahwee** [nodejs/docs#102]
Can we standardize on the file paths in the documentation?

Surfaced by [this issue](https://github.com/nodejs/node/issues/6431), we have `/Users/mjr` in [Global Objects]() being used as the directory. 

Other instances:
- `/Users/maciej` in [process](https://nodejs.org/api/process.html)
- `/home/indutny/Code/git/indutny/` in [debugger](https://nodejs.org/api/debugger.html)
- `/home/gbusey/` in [errors](https://nodejs.org/api/errors.html)

Suggestions:
- `/path/to/<something>`
- `/foo/bar/<something>`

What do you all think?

**Comment by benjamingr** [comment]
I kind of like the fact real usernames are used and the users don't mind.

Any concrete reason for this? I tend to be -1 on it as it creates some work but doesn't really save any

**Comment by estliberitas** [comment]
-1 for the same reason as @benjamingr 

I think, users usually find it more friendly when near-real paths, names and data is used in examples. Helps to project usage of APIs on their cases.

But, same time, I think, if it's a new doc, we better use generic path like @kahwee suggests. Just because it's generic i.e. universal case.

**Comment by mscdex** [comment]
IMHO I think if we're going to stay with home directories, it's best to at least make the paths consistent, with my preference being `/home/...` instead of `/Users/...`.

I also think that using `/home/user` is better than `/home/<specific username>` since it is less confusing but is still equivalent in intent.

**Comment by eljefedelrodeodeljefe** [comment]
I am in support of @mscdex's proposal.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
