### ISSUE TITLE
Official documentation: piping curl to shell for installation

### ISSUE THREAD

**Issue by CalvinHartwell** [nodejs/docs#106]
This has probably been mentioned before, but I believe this is pretty bad practice ([https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora))

curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -

To completely understand why it is bad practice, please see this:

[https://www.seancassidy.me/dont-pipe-to-your-shell.html](https://www.seancassidy.me/dont-pipe-to-your-shell.html)

and this: 

[https://news.ycombinator.com/item?id=6650987](https://news.ycombinator.com/item?id=6650987)

To fix it, the steps should be: 

curl --silent --location https://rpm.nodesource.com/setup_4.x > install-node.sh && chmod 500 install-node.sh && ./install-node.sh

Can we get this fixed?

Cheers,
- Calvin

**Comment by bnoordhuis** [comment]
> curl --silent --location https://rpm.nodesource.com/setup_4.x > install-node.sh && chmod 500 install-node.sh && ./install-node.sh

You may want to elaborate on why you think that is a proper fix.

**Comment by eljefedelrodeodeljefe** [comment]
Hi Calvin,

This was discussed in many ways and I think once you look at the script (and you should or at least trust the source) it should be alright. Consider this [link from reddit of some days ago](https://www.reddit.com/r/node/comments/4i6cor/is_nodesource_crazy/) where you see a lively discussion. Since there are plenty of alternatives and also problems with external package managers on the unixes I would regard this as a pretty fine solution, which raises less questions then your script above. If in doubt build from source, which in node is super easy (thanks!) on all the platforms.

By the way docker alternatives would build from source or do the bash script piping above, without letting users knowing it - unless they look for it.

If no-one disagrees I am gonna close this.

**Comment by CalvinHartwell** [comment]
Sorry I was blunt, I should really have explained it better. 

> You may want to elaborate on why you think that is a proper fix.

I believe the scenario described in this link is actually present in the script: [https://www.seancassidy.me/dont-pipe-to-your-shell.html](https://www.seancassidy.me/dont-pipe-to-your-shell.html)

RPM_TMP=$(mktemp || bail)
exec_cmd "rm -f '${RPM_TMP}'

So, if the connection is closed mid stream, you could remove some things accidentally from the temp dir and the user would not be aware of it. 

My version of the command would not attempt to execute the script if curl had failed (non zero error code from timeouts, etc). It may also be a good idea to remove the --silent incase there has been an issue with curl (for example, if a proxy blocks nodejs.org, it will fail silently). 

I also have an issue with the EPEL5 fix but that is another story...

**Comment by eljefedelrodeodeljefe** [comment]
Can you take this to https://github.com/nodesource/distributions as described in the script? The points are valid, Let's see if the guys from nodesource want to include it. Maybe they have some insight about this already.

**Comment by CalvinHartwell** [comment]
Sure thing - I will do that now, thanks for the quick replies!

**Comment by rvagg** [comment]
Cross-porting part of my response from the issue opened over at nodesource/distributions because we have to deal with complaints about `curl|bash` on a regular basis, for various reasons; this particular one is new(ish) and not so much about security as per usual, but the response is still the same:

> We provide an easy curl|bash solution for convenience but also provide manual instructions on the README for people who dislike the practice for whatever reason. At this stage we're going to continue to offer the simple version and extended version rather than opt for something in between.

i.e. to paraphrase the sentiment: you don't have to use it if you don't like it, and we're not going to change it because you don't like it, we provide a clear alternative just for you.

We don't buy in to the common arguments that energise people so much about `curl|bash` (even though there exists [this fascinatingly evil example](https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/)). It's all about trust, and that's something you have to exercise whether you're offered a `curl|bash` solution, a direct executable download, an `npm install`, `brew install` and even an `apt-get install`. If you don't trust NodeSource to code up a Bash script and serve it to you securely then manually install using the instructions provided. If you don't trust NodeSource at all, download from nodejs.org or build from source. That's how the internet works.
